### ISSUE TITLE
Certificate validity and expiration time bug

### ISSUE THREAD

**Issue by pjsramos** [ehn-digital-green-development/hcert-kotlin#1]
I think there is a bug with DecisionService.

In line 33, this service is verifying that signing certificate's expiration date is not after DGC expiration time. This does not seem ok because the validity of the signing certificate must be greater than the validity off the signed document.

```
31      verificationResult.expirationTime?.let { expirationTime ->
32            verificationResult.certificateValidUntil?.let { certValidUntil ->
33                if (certValidUntil.isAfter(expirationTime))
34                    return VerificationDecision.FAIL
35            }
36            if (expirationTime.isBefore(Instant.now()))
37                return VerificationDecision.FAIL
38        }
```

**Comment by nodh** [comment]
@pjsramos You're absolutely right, thanks for spotting that mistake!
