### ISSUE TITLE
Truncate kid

### ISSUE THREAD

**Issue by M3kH** [ehn-digital-green-development/hcert-kotlin#2]
I browse a bit trough the implementations, and I couldn't see where the `Kid` gets truncated (at 8 bytes).

Is this implementation following this [specs](https://github.com/ehn-digital-green-development/hcert-spec/blob/main/hcert_spec.md#a1-the-key-identifier-kids) ?

**Comment by asitplus-pteufl** [comment]
Yeah, it follows the specs (hopefully :-), this is the chain as it is going to be used in Austria for QR generation.
You can find the code [here](https://github.com/ehn-digital-green-development/hcert-kotlin/blob/23203fbb71f53524ee643a9df116264f87b5b32a/src/main/kotlin/ehn/techiop/hcert/kotlin/chain/impl/RandomEcKeyCryptoService.kt#L28): 
which refers to PKIUtils: the specific line is [here](https://github.com/ehn-digital-green-development/hcert-kotlin/blob/23203fbb71f53524ee643a9df116264f87b5b32a/src/main/kotlin/ehn/techiop/hcert/kotlin/chain/common/PkiUtils.kt#L35):

**Comment by M3kH** [comment]
@asitplus-pteufl Thanks for the answer!
