### ISSUE TITLE
Introduce Tags for Versioning

### ISSUE THREAD

**Issue by psavva** [ehn-digital-green-development/hcert-kotlin#5]
Currently, every time the library is updated, it's very difficult and cumbersome to try and figure out exactly which Snapshot version contains which github code (ie: at what point was the snapshot published?)

May I request that the library is tagged with the exact snapshots, and everytime there are official releases, tags are maintained?

**Comment by nodh** [comment]
Thanks for the suggestion, I'll try to keep that up-to-date. But I would strongly suggest forking this repository internally if you really depend on it.
